#lifted from: https://github.com/angular/angular-seed/blob/master/.travis.yml
language: node_js
node_js:
  - '0.10'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm install -g bower
  - bower install
  - node_modules/karma/bin/karma start tests/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox

